"""State schemas for LangGraph workflows."""

import operator
from typing import Annotated, Any, Dict, List, Optional
from pydantic import BaseModel, Field
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage

#
# Planner Output Schema
#
class SubTask(BaseModel):
    """A research subtask generated by the planner."""
    entity_name: str = Field(description="Name of the person, event, or organization to research")
    entity_type: str = Field(description="Type of the entity (Person, Event, Organisation)")
    research_query: str = Field(description="Specific research question or query to pursue")

class ResearchPlan(BaseModel):
    """Overall research plan produced by the planner."""
    main_topic: str = Field(description="The high level topic being researched")
    subtasks: List[SubTask] = Field(description="List of specific entities and questions to investigate")

#
# Overall Graph State
#
class OrchestratorState(TypedDict):
    """The state of the top-level workflow."""
    query: str
    messages: Annotated[list[BaseMessage], operator.add]
    plan: Optional[ResearchPlan]
    
    # Track results from sub-agents
    agent_results: Annotated[List[Dict[str, Any]], operator.add]
    
    # State tracking and refinement
    loop_count: int
    user_approved_plan: bool
    
    # Master results
    master_report: Optional[str]
    suggested_gaps: List[str] # Overwrites on each iteration

#
# Sub-Agent State
#
class ResearcherState(TypedDict):
    """State for an individual researcher sub-agent."""
    run_id: str
    agent_id: str
    subtask: SubTask
    
    # Internal messaging for the subagent LLM reasoning
    messages: Annotated[list[BaseMessage], operator.add]
    
    # Results
    final_report: str
    structured_data: Dict[str, Any]
